name: workflow-ci-env
channels:
  - defaults
dependencies:
  - python=3.12.7
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip
  - pip:
      - mlflow==2.19.0
      - joblib
      - cloudpickle